config/routes.rb
Fustal::Application.routes.draw do
  # Publication
  resources :articles, as: 'articles', path: App::Naming::BLOG.downcase, only: [:show, :index]

  post '/send_contact_email', to: 'application#send_contact_email', as: :send_contact_email

  # Safina
  get '/safina/payment_redirect', to: 'safina#redirector', id: 'redirector'
  get '/safina', to: 'safina#landing', as: 'safina_root'
  get '/safina/help', to: 'safina#help', as: 'safina_knowledge_base'
  get '/safina/aqad', to: 'safina#sharia_compliance', as: 'safina_sharia_compliance'
  get '/safina/contact', to: 'safina#contact', as: 'safina_contact_page'
  get '/safina/order', to: 'safina#order_form', as: 'safina_order_form'
  get '/safina/d', to: 'safina#view_card', as: 'safina_view_card'
  post '/safina/d/open', to: 'safina#open_card', as: 'safina_open_card'
  post '/safina/d/reload', to: 'safina#request_reload_card', as: 'safina_request_reload_card'

  # Auth0
  get '/auth/auth0/callback' => 'auth0#callback'
  delete '/auth/auth0/logout' => 'auth0#logout'
  get '/auth/failure' => 'auth0#failure'

  # New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'avatar'
      put 'remove_avatar'
    end
  end

  # Static Pages
  get '/failed_payment', to: 'pages#show', id: 'failed_payment'
  get '/id/*id' => 'pages#show', as: :page, format: false
  
  # Error pages
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable'
  get '/500' => 'errors#internal_server_error'

  namespace :admin do
    root 'base#index'
    resources :users
    resources :articles, only: [:index] do
      collection { post 'bulk_sync' }
      member { post 'sync' }
    end

    # SAFINA Admin
    get 'safina/prepare_invoice', to: 'safina#prepare_invoice'
    post 'safina/create_invoice', to: 'safina#create_invoice'

    get 'safina/prepare_reload_payment_notif', to: 'safina#prepare_reload_payment_notif'
    post 'safina/send_reload_payment_notif', to: 'safina#send_reload_payment_notif'
  end

  # Robot script
  get '/robots.txt' => RobotsTxt

  # Root
  root to: 'articles#index'
end

app/controllers/admin/safina_controller.rb
module Admin
  class SafinaController < BaseController
    def prepare_invoice
    end

    def prepare_reload_payment_notif
    end

    def create_invoice
      params[:merchantCode] = ENV['DUITKU_SAFINA_MERCHANT_CODE']
      params[:paymentMethod] = 'BT'
      params[:callbackUrl] = ENV['DUITKU_SAFINA_CALLBACK_URL']
      params[:returnUrl] = 'sikapiten.com/safina/payment_redirect'
      params[:category] = 'PURCHASE'

      require 'digest/md5'
      combined_input = params[:merchantCode] + params[:merchantOrderId] +
                       params[:paymentAmount] + ENV['DUITKU_SAFINA_KEY']
      signature = Digest::MD5.hexdigest(combined_input)

      params[:signature] = signature

      res = NetRequestInterface.new(ENV['DUITKU_API_URL'] + 'inquiry').send_post_request(params)

      if res.success?
        invoice_data = JSON.parse(res.body)

        client = AirtableClient.new(extension: ENV['AIRTABLE_SAFINA'])
        invoice_fields = {
          :Category => params[:category],
          :"Merchant Order ID" => params[:merchantOrderId],
          :"Invoice Page URL" => invoice_data['paymentUrl'],
          :Signature => signature,
          :Provider => "Duitku",
          :"Provider Invoice ID" => invoice_data['reference'],
          :"Merchant User Info" => params[:merchantUserInfo],
          :Email => params[:merchantUserInfo],
          :Amount => params[:paymentAmount]
        }
        invoice_input = { :fields => invoice_fields }.to_json

        second_res = client.send_post_request(endpoint: 'Invoice', data: invoice_input)

        if second_res.success?
          airtable_invoice_response = JSON.parse(second_res.body)
          transaction_fields = {
            :"Prepaid Card" => [params[:merchantOrderId]],
            :Invoice => [airtable_invoice_response['id']]
          }
          transaction_input = { :fields => transaction_fields }.to_json

          third_res = client.send_post_request(endpoint: 'Transaction', data: transaction_input)

          if third_res.success?
            flash[:notice] = 'Successfully sent request to create transaction record'
          else
            flash[:notice] = 'Successfully sent request to create invoice'
          end
        else
          flash[:alert] = 'Failed request to create invoice'
        end
      else
        flash[:alert] = 'Failed request to create invoice'
      end

      redirect_to admin_safina_prepare_invoice_path
    end

    def send_reload_payment_notif
      if params[:transactionUUID].present?
        query = "maxRecords=1&view=Grid%20view&filterByFormula=({UUID} = #{params[:transactionUUID]})"
        endpoint = 'Transaction?' + query

        client = AirtableClient.new(extension: ENV['AIRTABLE_SAFINA'])
        res = client.send_get_request(endpoint: endpoint)

        invoice_data = JSON.parse(res.body)
        payload = invoice_data['records'][0]['fields']
        humanized_amount = ActionController::Base.helpers.number_to_currency(
          payload['Value'][0], unit: 'Rp ', delimiter: '.', separator: ','
        )

        delivery = SafinaTransactionMailer.card_reload_payment_notif(
          payload['Payer Name'][0], 
          payload['Payer Email'][0], 
          payload['Card Label'][0], 
          humanized_amount, 
          payload['Payment URL'][0]
        )

        if delivery['code'] == 'success'
          flash[:notice] = 'Payment prompt has been delivered'
        else
          flash[:alert] = 'Failed to deliver payment prompt'
        end
      else
        flash[:alert] = 'Invalid input, please try again'
      end

      redirect_to admin_safina_prepare_reload_payment_notif_path
    end
  end
end

app/controllers/safina_controller.rb
class SafinaController < ApplicationController
  before_filter :set_meta_keywords, except: [
    :view_card, :open_card
  ]
  before_filter :prepare_card, only: :view_card
  skip_before_filter :verify_authenticity_token, only: :request_reload_card


  def landing
  	@title = App::Title::CARD
  end

  def help
  	@title = 'Bantuan |' + App::Title::CARD
  end

  def sharia_compliance
  end

  def order_form
    require 'bigdecimal'

  	@title = 'Formulir Pemesanan |' + App::Title::CARD
    @usd_amount = params[:usd_amount]

    if @usd_amount.present?
      uri = URI.parse(ENV['CURRENCYLAYER_API_URL'] + "?access_key=#{ENV['CURRENCYLAYER_API_KEY']}&currencies=IDR")
      http = Net::HTTP.new(uri.host, uri.port)
      request = Net::HTTP::Get.new(uri.request_uri)

      response = JSON.parse http.request(request).body.as_json
      rate = BigDecimal.new(response['quotes']['USDIDR'])
      @idr_amount = BigDecimal.new(@usd_amount.to_i + 5) * rate
    end
  end

  def view_card
    render layout: false
  end

  def open_card
    crypt = setup_simple_crypt

    if params[:password] == crypt.decrypt_and_verify(params[:cardKey]) 
      render status: :ok, json: { 'status' => 'success' }
    else
      render status: :unprocessable_entity, json: { 'status' => 'failed' }
    end
  end

  def request_reload_card
    @success = false

    if BigDecimal.new(params[:amount].gsub(',', '.')) >= BigDecimal.new('25.00')
      client = AirtableClient.new(extension: ENV['AIRTABLE_SAFINA'])

      form_fields = {
        :"PrepaidCard" => [params[:card]],
        :"Amount" => params[:amount],
        :"Status" => 'PENDING'
      }
      reload_input = { :fields => form_fields }.to_json

      res = client.send_post_request(endpoint: 'ReloadForm', data: reload_input)
      @success = true if res.success?
    end

    respond_to do |format|
      format.js do 
        if @success
          flash.now[:notice] = 'Terima kasih, kami akan mengontakmu via email'
        else
          flash.now[:danger] = 'Maaf, mohon coba lagi'
        end
      end
    end
  end

  def redirector
    # returned params by Duitku
    merchant_invoice_uid = params[:merchantOrderId]
    provider_invoice_uid = params[:reference]
    status = params[:resultCode]

    if status.to_s == '00'
      # Immediately send paying customer to the card page
      redirect_to safina_view_card_path(card: merchant_invoice_uid, xyz: reference)
    else #could be 01 or 02, which means pending/failed or cancelled
      redirect_to failed_payment_path
    end
  end

  private

  def set_meta_keywords
    @keywords = 'Kartu kredit syariah, kartu prabayar Visa, kartu virtual, belanja online'
  end

  def prepare_card(authenticated: false)
    begin
      raise ArgumentError if params['card'].nil?

      retrieve_card_attributes(card: params['card'])

      last_digits_number = @card_attributes['card_number'].split(' ').last
      @card_attributes['masked_card_number'] = '**** **** **** ' + last_digits_number
      @card_attributes['masked_expiry_date'] = '**/**'
      @card_attributes['masked_cardholder_name'] = @card_attributes['cardholder_name'].gsub(/[a-zA-z]/, '*')        
      @card_attributes['initial_balance'] = @card_attributes['initial_balance'].to_sentence

      @card = SafinaCard.new(@card_attributes)
      raise ArgumentError if @card.nil?

      gon.push({
        maskedCardholderName: @card.masked_cardholder_name,
        maskedCardNumber: @card.masked_card_number,
        maskedExpiryDate: @card.masked_expiry_date,
        cardNumber: @card.card_number,
        cardholderName: @card.cardholder_name,
        expiryDate: @card.expiry_date
      })

      if params[:xyz].present?
        SafinaJob::RecordHandover.perform_later(
          @card_attributes['cardholder_name'],
          @card_attributes['email'].to_sentence,
          @card_attributes['uuid'],
          @card_attributes['card_url']
        )
      end      

      @card_key = encrypt_card_key(
        plain_key: @card_attributes['zipcode'].first + @card_attributes['phone_number'].first
      )
    rescue ArgumentError
      redirect_to '/404' and return
    end
  end

  def retrieve_card_attributes(card:)
    client = AirtableClient.new(extension: ENV['AIRTABLE_SAFINA'])
    api_response = client.send_get_request(endpoint: "PrepaidCard/#{card}")
    
    raise ArgumentError if api_response.status.to_s != '200'
    valid_keys = [
      'Expiry Date', 'Status', 'Card Number', 'UUID', 'Currency', 'Card URL',
      'Current Balance', 'Initial Balance', 'Issued At', 'Last Checked At',
      'Cardholder Name', 'Phone Number', 'Email', 'Zipcode', 'Code',
    ]

    attributes_hash = JSON.parse(api_response.body)['fields'].slice(*valid_keys)
    attributes_hash['Code'] = attributes_hash['Code'].split('-').last
    attributes_hash['UUID'] = attributes_hash['UUID'].split('-').first.upcase

    @card_attributes = attributes_hash.transform_keys{ |key| key.strip.gsub(' ', '_').underscore }
  end

  def setup_simple_crypt
    key = ActiveSupport::KeyGenerator.new('card_password')
                                     .generate_key(ENV['CARD_SALT'])
    ActiveSupport::MessageEncryptor.new(key)
  end

  def encrypt_card_key(plain_key:)
    crypt = setup_simple_crypt

    crypt.encrypt_and_sign(plain_key)  
  end
end

app/views/safina/_authenticated_card.html.erb
<div id="authenticated-card" class="text-center" style="display: none;">
  <div class="jp-card-container" id="authenticated-info">
    <p><small><em>Kartu ini akan tertutup dengan sendirinya dalam 30 detik</em></small></p>
    <p><%= link_to 'Isi ulang kartu', '#', class: 'btn btn-sm btn-primary', id: 'reload-card-btn' %></p>
    <p>
      <span class="card-detail-key">CVC/Security Code</span>
      <span class="card-detail-value"> <%= @card.code %></span>
    </p>
    <p>
      <span class="card-detail-key">Terakhir dicek</span>
      <span class="card-detail-value"> <%= humanized_last_checked_at(@card.last_checked_at) %></span>
    </p>
    <p>
      <span class="card-detail-key">Saldo</span>
      <span class="card-detail-value"> <%= show_card_balance(@card) %></span>
    </p>
    <p>
      <span class="card-detail-key">Status</span>
      <span class="card-detail-value"> <%= show_card_status(@card.status) %></span>
    </p>
    <p>
      <span class="card-detail-key">Dibuat</span>
      <span class="card-detail-value"> <%= humanized_issued_at(@card.issued_at) %></span>
    </p>
  </div>

  <div id="reload-form" class="well" style="display:none;">
    <button type="button" id='close-reload-card-form' class="close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    
    <br>
    
    <p class="text-left"><small>Silahkan masukkan jumlah saldo USD yang kamu inginkan, minimal 25 USD</small></p>

    <%= form_tag safina_request_reload_card_path(card: params[:card]), remote: true, method: 'post', class: 'custom-search-input', id: 'reload-card-form' do %>
      <div class="input-group col-md-12">
        <%= text_field_tag :amount, '', placeholder: 'gunakan koma sebagai desimal', class: 'form-control input-lg' %>
        <span class="input-group-btn">
          <%= button_tag(type: "submit", class: "btn btn-md btn-info") do %>
            <i class="glyphicon glyphicon-ok"></i>
          <% end %>
        </span>
      </div>
    <% end %><br>
    <span class="card-detail-value"><strong>Saldo saat ini:</strong> <%= show_card_balance(@card) %></span>
  </div>  
</div>

app/views/safina/_faq_items.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4 class="panel-title">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<%= id %>">
        <%= title %>
      </a>
    </h4>
  </div>
  <div id="<%= id %>" class="panel-collapse collapse in">
    <div class="panel-body">
      <%= raw answer %>
    </div>
  </div>
</div>

app/views/safina/_footer.html.erb
<footer id="fh5co-footer" role="contentinfo">
  <div class="container">
    <div class="row row-pb-md">
      <div class="col-md-1"></div>
      <div class="col-md-7 col-sm-8 fh5co-widget" style="text-align: left;">
        <h3><%= App::Naming::CARD %> by Kapiten.</h3>
        <p><%= App::Description::CARD %></p>
        <p>
          <%= active_link_to "Telusuri #{App::Naming::BLOG} Kapiten", root_path, active: false %>
        </p>
      </div>
      <div class="col-md-3 col-sm-4">
        <ul class="fh5co-footer-links" style="text-align: right;color: grey;">
          <%= active_link_to 'Tanya-jawab', safina_knowledge_base_path, active: false, wrap_tag: :li %>
        	<%= active_link_to 'Tentang Kapiten', page_path(id: 'about'), active: false, wrap_tag: :li %>
					<%= active_link_to 'Hubungi Kami', page_path(id: 'contact'), active: false, wrap_tag: :li %>
          <%=
            #active_link_to 'Syarat dan Ketentuan', page_path(id: 'card_terms'), active: false, wrap_tag: :li 
          %>
          <li>
            <a href="https://www.facebook.com/kapitenmuamalah" target= "_blank">Majlis Muamalah</a>
          </li>
          <li>
            <a href="https://www.facebook.com/groups/majlis.muamalah" target= "_blank">Facebook Page</a>
          </li>
        </ul>
      </div>
      <div class="col-md-1"></div>
    </div>

    <div class="row copyright">
      <div class="col-md-12 text-center">
        <p>
          <small class="block">&copy; 2017 PT Kapiten Teknologi Indonesia</small>
        </p>
      </div>
    </div>

  </div>
</footer>

app/views/safina/_navigation.html.erb
<nav class="fh5co-nav" role="navigation">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 text-center">
        <div id="fh5co-logo">
          <%= link_to safina_root_path do %>
            <%= App::Naming::CARD %><span>.</span>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 text-center menu-1">
        <ul>
          <%= active_link_to 'Intro', safina_root_path, active: :exclusive, wrap_tag: :li %>
          <%= active_link_to 'Bantuan', safina_knowledge_base_path, active: :exclusive, wrap_tag: :li %>
          <%= active_link_to 'Pesan', safina_order_form_path, active: :exclusive, wrap_tag: :li %>
          <%= active_link_to 'Profil', page_path(id: 'about'), active: :exclusive, wrap_tag: :li %>
          <%= active_link_to 'Kontak', page_path(id: 'contact'), active: :exclusive, wrap_tag: :li %>
        </ul>
      </div>
    </div>

  </div>
</nav>

app/views/safina/_unauthenticated_card.html.erb
<div id="unauthenticated-card" class="text-center">
  <p>
    <small>
      Untuk membuka tampilan kartu secara penuh, masukkan <strong>kode pos dan nomor telepon</strong> (tanpa spasi) yang kamu daftarkan di kotak di bawah ini.
    </small>
  </p>

  <%= form_tag safina_open_card_path(card: params[:card]), method: 'post', class: 'custom-search-input', id: 'card-lock-form' do %>
    <div class="input-group col-md-12">
      <%= password_field_tag :password, '', placeholder: 'Password: [kodepos][telp]', class: 'form-control input-lg', id: 'password-input' %>
      <%= hidden_field_tag 'cardUID', params[:card] %>
      <%= hidden_field_tag 'cardKey', @card_key %>
      <span class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-info btn-lg") do %>
          <i class="glyphicon glyphicon-log-in"></i>
        <% end %>
      </span>
    </div>
  <% end %>
</div>

app/views/safina/help.html.erb
<% content_for :head do %>
  <html itemscope itemtype="http://schema.org/Product">
  <meta name="keywords" content="<%= @keywords %>">

  <meta itemprop="name" content="<%= App::Title::CARD %>">
  <meta itemprop="description" content="<%= App::Description::CARD %>">
  <meta itemprop="image" content="<%= App::Source::CARD_IMAGE %>">
  <meta itemprop="url" content="<%= safina_root_url %>">

  <meta property="fb:app_id" content="<%= ENV["FB_APP_ID"] %>" />
<% end %>
<%
  set_meta_tags og: {
    image: App::Source::CARD_IMAGE,
    site_name: App::Title::CARD + ' | ' + ENV["SITE_NAME"],
    title: :title,
    description: App::Description::CARD,
    type: 'product.item',
    locale: 'id_ID',
    url: safina_root_url
  }
%>
<%
  set_meta_tags title: App::Title::CARD,
  description: App::Description::CARD
%>

<header id="fh5co-header" class="fh5co-cover" role="banner">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center">
        <div class="display-t">
          <div class="display-tc animate-box" data-animate-effect="fadeInUp">
            <h1 class="mb30">Knowledge Base</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>



<div id="fh5co-blog" class="fh5co-bg-section">
  <div class="container">
    <div class="row animate-box row-pb-md" data-animate-effect="fadeInUp">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <span>Beragam pertanyaan yang ada di benakmu dan jawaban kami</span>
        <h2>Tanya-Jawab</h2>
      </div>
    </div>
    <div class="row">
      <div class="panel-group" id="accordion">
        <div class="faqHeader">Pertanyaan Umum</div>
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_1',
            title: 'Apa yang dimaksud dengan kartu Safina?',
            answer: 'Kartu Safina adalah kartu Visa prabayar yang berbentuk virtual, dengan kata lain tidak ada bentuk fisiknya. Kartu Safina memiliki karakteristik seperti kartu kredit Visa seperti nomor, tanggal kadaluwarsa, nama pemilik, dan security number.'
          }
        %>
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_2',
            title: 'Dapat dipakai dimana?',
            answer: 'Kartu Safina dapat digunakan di berbagai situs online internasional, baik untuk pembelian atau pembayaran subscription. Tetapi kartu Safina tidak dapat digunakan untuk belanja di situs lokal, seperti Tokopedia dan Lazada, sebagai kartu kredit.'
          }
        %>
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_3',
            title: 'Bagaimana jika situs online yang saya akan lakukan pembayaran menolak kartu Safina?',
            answer: 'Untuk kasus langka seperti ini, kami menyarankan untuk kamu membuat akun Paypal dan menghubungkannya dengan kartu Safinamu. Ini akan membuat kamu dapat membayar tagihan situs tersebut menggunakan Paypal, yang menggunakan saldo kartu Safina.'
          }
        %>

        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_4',
            title: 'Saya tidak mau repot membuat akun paypal, saya lebih memilih untuk refund.',
            answer: 'Tentu saja, refund untuk kartu Safina dapat dilakukan selama belum melewati 10 hari dari tanggal pembelian dan saldo kartu masih belum digunakan sama sekali.'
          }
        %>
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_5',
            title: 'Bagaimana cara saya membayar?',
            answer: "Pembayaran dapat dilakukan dengan transfer bank. Ketika kartu yang dipesan sudah siap, kamu akan mendapatkan email yang mengarahkan kamu ke halaman pembayaran yang memberi tahu nomor rekening tujuan transfer."
          }
        %>
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_5',
            title: 'Adakah biaya dari menggunakan kartu Safina?',
            answer: "Ada biaya 1 USD per bulan yang dikenakan oleh issuer dari kartu Visa prabayar yang menjadi basis kartu Safina. 1 USD ini per bulannya akan ditarik dari saldo kartumu. Apabila kartu memiliki saldo negatif selama 3 bulan berturut-turut, kartu akan dibatalkan secara otomatis."
          }
        %>
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_6',
            title: 'Apakah saya perlu menyerahkan dokumen identitas?',
            answer: "Selama total akumulasi penggunaan kartumu di bawah 1000 USD, kamu tidak akan diminta untuk menyerahkan dokumen apapun. Namun ketika kamu telah membelanjakan total 1000 USD dengan kartu tersebut, maka hasil scan/foto identitas diri, dapat berupa KTP atau Passport, dan hasil scan bukti domisili, seperti rekening koran atau tagihan telepon dengan namamu, wajib diserahkan."
          }
        %>                
        <%=
          render partial: 'faq_items', locals: {
            id: '#faq_7',
            title: 'Saya menghindari memiliki kartu kredit karena itu melanggar syariah Islam. Apa ini sesuai dengan syariah?',
            answer: "Insya Allah, kami berusaha dengan keras dalam menstruktur transaksi dan akad yang digunakan agar dapat mencapai hal tersebut. Bagi kamu yang ingin tahu penjelasan lebih dalam mengenai aspek akad kartu Safina, silahkan klik link <a href='/safina/aqad'>ini</a>."
          }
        %>
      </div>
    </div>
  </div>
</div>


<div id="fh5co-started">
  <div class="container">
    <div class="row animate-box">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <span>Sudah siap untuk memesan?</span>
        <h2>Kartu <%= App::Naming::CARD %></h2>

        <p>
  <%=
            link_to 'Ke Halaman Pemesanan',
                    safina_order_form_path,
                    class: 'btn btn-primary'
          %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/safina/order_form.html.erb
<% content_for :head do %>
  <html itemscope itemtype="http://schema.org/Product">
  <meta name="keywords" content="<%= @keywords %>">

  <meta itemprop="name" content="<%= App::Title::CARD %>">
  <meta itemprop="description" content="<%= App::Description::CARD %>">
  <meta itemprop="image" content="<%= App::Source::CARD_IMAGE %>">
  <meta itemprop="url" content="<%= safina_root_url %>">

  <meta property="fb:app_id" content="<%= ENV["FB_APP_ID"] %>" />
<% end %>
<%
  set_meta_tags og: {
    image: App::Source::CARD_IMAGE,
    site_name: App::Title::CARD + ' | ' + ENV["SITE_NAME"],
    title: :title,
    description: App::Description::CARD,
    type: 'product.item',
    locale: 'id_ID',
    url: safina_root_url
  }
%>
<%
  set_meta_tags title: App::Title::CARD,
  description: App::Description::CARD
%>

<header id="fh5co-header" class="fh5co-cover" role="banner">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-md-offset-0 text-center">
        <div class="display-t">
          <div class="display-tc animate-box" data-animate-effect="fadeInUp">
            <h1 class="mb30">Pemesanan Kartu Safina</h1>
            <p class="mb30"></p>
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 text-center">
              <h5 class="white">Simulasi Harga Kartu</h5>
              <% if params[:usd_amount] %>
                <h3 class="white"><%= number_to_currency(@idr_amount, unit: "Rp ", delimiter: ".", precision: 0) %></h3>
                <p class="white mb30"><small>sudah termasuk fee sebesar 5 USD untuk Kapiten</small></p>
              <% end %>
              <%= form_tag safina_order_form_path, method: :get do %>
              <div class="input-group number-spinner">
                <span class="input-group-btn">
        					<button class="btn btn-default disabled" style="cursor:default;"><span class="glyphicon glyphicon-usd"></span></button>
        				</span>
                <%= text_field_tag 'usd_amount', params[:usd_amount] || '25', class: 'form-control text-center', style: 'background:white;' %>
        				<span class="input-group-btn">
        					<button class="btn btn-default full-width"><span class="glyphicon glyphicon-search"></span></button>
        				</span>
        			</div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>



<div>
  <div class="container">
    <div class="row">
      <script src="https://static.airtable.com/js/embed/embed_snippet_v1.js"></script>
      <% if Rails.env.production? %>
        <iframe class="airtable-embed airtable-dynamic-height" src="https://airtable.com/embed/shrhWSRxenPq5dpOk?backgroundColor=teal" frameborder="0" onmousewheel="" width="100%" height="2104.75" style="background: transparent; border: 1px solid #ccc;"></iframe>
      <% else %>
        <iframe class="airtable-embed airtable-dynamic-height" src="https://airtable.com/embed/shr4HvXw9DXOKuARF?backgroundColor=purple" frameborder="0" onmousewheel="" width="100%" height="1387.2" style="background: transparent; border: 1px solid #ccc;"></iframe>
      <% end %>
    </div>
  </div>
</div>


<div id="fh5co-started">
  <div class="container">
    <div class="row animate-box">
      <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
        <span></span>
        <h2>Masih ragu atau ada yang ingin ditanyakan?</h2>

        <p>
          <%= link_to "Hubungi Kami", page_path(id: 'contact'), class: 'btn btn-default' %>
        </p>
        <p><small>atau silahkan kunjungi <%= link_to "halaman Bantuan", safina_knowledge_base_path, class: 'secondary-link' %> kami</small></p>
      </div>
    </div>
  </div>
</div>

<style type="text/css">
  .white { color: white; }
</style>
<script type="text/javascript">
</script>