config/routes.rb
Fustal::Application.routes.draw do
  # Publication
  resources :articles, as: 'articles', path: App::Naming::BLOG.downcase, only: [:show, :index]

  post '/send_contact_email', to: 'application#send_contact_email', as: :send_contact_email

  # Safina
  get '/safina/payment_redirect', to: 'safina#redirector', id: 'redirector'
  get '/safina', to: 'safina#landing', as: 'safina_root'
  get '/safina/help', to: 'safina#help', as: 'safina_knowledge_base'
  get '/safina/aqad', to: 'safina#sharia_compliance', as: 'safina_sharia_compliance'
  get '/safina/contact', to: 'safina#contact', as: 'safina_contact_page'
  get '/safina/order', to: 'safina#order_form', as: 'safina_order_form'
  get '/safina/d', to: 'safina#view_card', as: 'safina_view_card'
  post '/safina/d/open', to: 'safina#open_card', as: 'safina_open_card'
  post '/safina/d/reload', to: 'safina#request_reload_card', as: 'safina_request_reload_card'

  # Auth0
  get '/auth/auth0/callback' => 'auth0#callback'
  delete '/auth/auth0/logout' => 'auth0#logout'
  get '/auth/failure' => 'auth0#failure'

  # New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'avatar'
      put 'remove_avatar'
    end
  end

  # Static Pages
  get '/failed_payment', to: 'pages#show', id: 'failed_payment'
  get '/id/*id' => 'pages#show', as: :page, format: false
  
  # Error pages
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable'
  get '/500' => 'errors#internal_server_error'

  namespace :admin do
    root 'base#index'
    resources :users
    resources :articles, only: [:index] do
      collection { post 'bulk_sync' }
      member { post 'sync' }
    end

    # SAFINA Admin
    get 'safina/prepare_invoice', to: 'safina#prepare_invoice'
    post 'safina/create_invoice', to: 'safina#create_invoice'

    get 'safina/prepare_reload_payment_notif', to: 'safina#prepare_reload_payment_notif'
    post 'safina/send_reload_payment_notif', to: 'safina#send_reload_payment_notif'
  end

  # Robot script
  get '/robots.txt' => RobotsTxt

  # Root
  root to: 'articles#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  include UserAdmin

  serialize :preferences, HashSerializer
  store_accessor :preferences,
                 :currency, :open, :understanding, :notification
  serialize :profile, HashSerializer
  store_accessor :profile,
                 :phone_number, :about, :last_education, :browser_id, :address,
                 :location, :marital_status, :work_experience, :occupation,
                 :number_dependents, :monthly_income, :monthly_expense

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable

  # Pagination
  paginates_per 30

  # Validations
  validates :name, presence: true
  validates :email, presence: true

  before_create :set_preferences!

  scope :omniauthers, lambda {
    where.not('profile @> ?', { auth_with: 'kapiten' }.to_json)
  }
  scope :admins, -> { where(admin: true) }

  def anonym_mask(post_ip:)
    'Anonim dengan IP address ' + post_ip.to_s
  end

  def registration_message
    "A user with email #{email} just registered"
  end

  def login_message
    "#{email} has just logged in"
  end

  private

  def set_preferences!
    self.currency = 'idr'
    self.open = 'yes'
    self.notification = 'yes'
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]
  
  add_breadcrumb "Users", :admin_users_path

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def new
    add_breadcrumb "Create New User", new_admin_user_path
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path
      flash[:notice] = "User successfully created."
    else
      render :new
      flash[:alert] = "User couldn't be updated."
    end
  end

  def edit
    add_breadcrumb "Edit", edit_admin_user_path(@user)
  end

  def update
    old_email = @user.email
    new_params = user_params.dup
    new_params[:email] = new_params[:email].strip

    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0

    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end

    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.email} updated."
    else
      flash[:alert] = "#{old_email} couldn't be updated."
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path 
    flash[:notice] = 'User was successfully destroyed.'
  end


  private

  def set_user
    @user = User.friendly.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :admin, :locked,
      :name, :phone_number, :understanding
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def render_user_thumb(options = {})
    AvatarRenderer.new(user_id: options[:user_id], css_class: options[:style]).thumbnail_display
  end

  def render_user_bigger_thumb(options={})
    AvatarRenderer.new(user_id: options[:user_id], css_class: options[:style]).profile_display
  end

  def user_education(user)
    education = if user.last_education.nil? then 'info pendidikan belum diisi' else user.last_education end
    content_tag(:p, education, id: 'user-education')
  end

  def user_occupation(user)
    occupation = if user.occupation.nil? then 'info pekerjaan belum diisi' else user.occupation end
    content_tag(:p, occupation, id: 'user-occupation')
  end

  def user_location(user)
    location = if user.location.nil? then 'info lokasi belum diisi' else "Tinggal di #{user.location}" end
    content_tag(:p, location, id: 'user-location')
  end

  def user_bio(user)
    bio = if user.about.nil? then 'bio belum diisi' else user.about end
    content_tag(:p, bio, id: 'user-bio')
  end

  def poster_identifier(post)
    if post.confidentiality?
      post.user_name
    else
      link_to post.user_name, user_path(post.user)
    end
  end
end

app/views/admin/users/edit.html.erb
<% title("Edit User Id: #{@user.id}") %>
<% content_for :main_actions do %>
  <%= link_to 'Ke Halaman Pengguna', user_path(@user) %>
<% end %>

<section class="intro padded bordered-section ">
  <div class="row">
    <div class="col-sm-12">
      <h1>User <small><%= "#{@user.name}" %></small></h1>
      <br>
    </div>
    <div class="spacing"></div>
    <div class="col-sm-6 col-md-4">
      <%= render_user_thumb(user_id: @user.id, style: 'img-circle circle-border m-b-md img-center') %>
    </div>
    <div class="col-sm-6 col-md-8">
      <h4>Edit Informasi Kunci</h4>
      <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>

        <div class="form-group">
          <%= f.label :email %>
          <div class="row">
            <div class="col-sm-12 col-md-10">
              <%= f.email_field :email, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :username %>
          <div class="row">
            <div class="col-sm-12 col-md-10">
              <%= f.text_field :username, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :avatar %>
          <div class="row">
            <div class="col-sm-12 col-md-10">
              <%= f.text_field :avatar, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :avatar_source %>
          <div class="row">
            <div class="col-sm-12 col-md-10">
              <%= f.text_field :avatar_source, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :auth_with %>
          <div class="row">
            <div class="col-sm-12 col-md-10">
              <%= f.text_field :auth_with, class: "form-control" %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-sm-6">
            <%= f.submit "Update User", class: "btn btn-success" %>
          </div>
        </div>

      <% end %>

    </div>
  </div>
</section>

<section class="intro padded bordered-section">

  <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
    <div class="inner-skeleton danger-zone">
      <h2>Danger Zone <br><small>Pertimbangkan dengan matang sebelum kamu menghapus akun ini</small></h2>
      <p></p>
      <p>
        <%= link_to admin_user_path(@user), method: :delete, data: {confirm: 'Kamu yakin mau melanjutkan?', object: 'Penghapusan pengguna'}, class: 'btn btn-danger btn-lg' do %>
            <span class="glyphicon glyphicon-trash reset-link"></span> Hapus Pengguna
        <% end %>
      </p>
    </div>
  </div>

</section>

app/views/admin/users/index.html.erb
<% set_meta_tags title title: "Users Panel" %>

<% content_for :main_actions do %>
<% end %>


<div class="text-center">
  <%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
      <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
    </p>
  <% end %>
</div>


<table class="table table-striped">
  <tr>
    <th>Email</th>
    <th>Admin</th>
    <th>Locked</th>
    <th>Sign up/in</th>
    <th></th>
  </tr>

  <% @users.each do |user| %>

  <tr id="no-<%= user.id %>">
    <td><%= truncate(user.email, length: 25) %><br><%= link_to user.name, user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.locked? ? "<b>yes</b>".html_safe : "no" %></td>
    <td>
      Joined on <%= user.created_at.strftime("%-d/%m/%Y") %><br>
    </td>
    <td><%= link_to "Kelola", edit_admin_user_path(user) %><br>
      <%= link_to "Impersonate", impersonate_engine.impersonate_user_path(user) unless current_user?(user) %>
    </td>
  </tr>

  <% end %>

</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>