config/routes.rb
Fustal::Application.routes.draw do
  # Publication
  resources :articles, as: 'articles', path: App::Naming::BLOG.downcase, only: [:show, :index]

  post '/send_contact_email', to: 'application#send_contact_email', as: :send_contact_email

  # Safina
  get '/safina/payment_redirect', to: 'safina#redirector', id: 'redirector'
  get '/safina', to: 'safina#landing', as: 'safina_root'
  get '/safina/help', to: 'safina#help', as: 'safina_knowledge_base'
  get '/safina/aqad', to: 'safina#sharia_compliance', as: 'safina_sharia_compliance'
  get '/safina/contact', to: 'safina#contact', as: 'safina_contact_page'
  get '/safina/order', to: 'safina#order_form', as: 'safina_order_form'
  get '/safina/d', to: 'safina#view_card', as: 'safina_view_card'
  post '/safina/d/open', to: 'safina#open_card', as: 'safina_open_card'
  post '/safina/d/reload', to: 'safina#request_reload_card', as: 'safina_request_reload_card'

  # Auth0
  get '/auth/auth0/callback' => 'auth0#callback'
  delete '/auth/auth0/logout' => 'auth0#logout'
  get '/auth/failure' => 'auth0#failure'

  # New App
  resources :users, only: [:show, :edit, :update] do
    member do
      get 'avatar'
      put 'remove_avatar'
    end
  end

  # Static Pages
  get '/failed_payment', to: 'pages#show', id: 'failed_payment'
  get '/id/*id' => 'pages#show', as: :page, format: false
  
  # Error pages
  get '/404' => 'errors#not_found'
  get '/422' => 'errors#unprocessable'
  get '/500' => 'errors#internal_server_error'

  namespace :admin do
    root 'base#index'
    resources :users
    resources :articles, only: [:index] do
      collection { post 'bulk_sync' }
      member { post 'sync' }
    end

    # SAFINA Admin
    get 'safina/prepare_invoice', to: 'safina#prepare_invoice'
    post 'safina/create_invoice', to: 'safina#create_invoice'

    get 'safina/prepare_reload_payment_notif', to: 'safina#prepare_reload_payment_notif'
    post 'safina/send_reload_payment_notif', to: 'safina#send_reload_payment_notif'
  end

  # Robot script
  get '/robots.txt' => RobotsTxt

  # Root
  root to: 'articles#index'
end

app/views/layouts/_admin_layout.html.erb
<header class="navbar navbar-inverse navbar-fixed-top " role="banner">
  <div class="container">
    <div class="navbar-header pull-left">
      <button href="#menu-toggle" type="button" class="navbar-toggle pull-left" id="menu-toggle" style="margin-top: 12px; margin-left: 12px;">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <a target="_blank" href="#" class="navbar-brand">Kapiten Back Office</a>
    </div>

    <div class="dropdown pull-right">
      <button class="btn btn-simple btn-sm btn-info dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        Hai, <%= current_user.name.titleize %>
      </button>
      <ul class="dropdown-menu">
        <li>
          <div class="navbar-login">
            <div class="row">
              <div class="col-lg-4">
                <p class="text-center">
                  <span class="glyphicon glyphicon-user icon-size"></span>
                </p>
              </div>
              <div class="col-lg-8">
                <p class="text-left"><strong><%= current_user.email %></strong></p>
                <p class="text-left">
                  <%= link_to 'Go To Main App', root_path, class: 'btn btn-primary btn-block btn-sm' %>
                </p>
              </div>
            </div>
          </div>
        </li>
        <li class="divider"></li>
        <li>
          <div class="navbar-login navbar-login-session">
            <div class="row">
              <div class="col-lg-12">
                <p>
                  <%= active_link_to 'Log out', auth_auth0_logout_path, data:{method: :delete}, class: 'btn btn-danger btn-block' %>
                </p>
              </div>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</header>

<div id="wrapper">

  <!-- Sidebar -->
  <%= render 'layouts/sidebar_wrapper' %>
  <!-- /#sidebar-wrapper -->

  <header class="main">
    <%= yield :main_actions %>
    <h2 class="products">
      <%= @page_title %> <%= render_breadcrumbs :separator => ' / ' %>
    </h2>
  </header>

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <%= render 'layouts/messages' %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12" id="innermost">
          <h2><%= yield :menu_title %></h2>
          <%= yield  %>
        </div>
      </div>
    </div>
  </div>
  <!-- /#page-content-wrapper -->

</div>

<script type="text/javascript">
$("#menu-toggle").click(function(e) {
  e.preventDefault();
  $("#wrapper").toggleClass("toggled");
});
</script>

app/views/layouts/_auth0_modal_lock_script.html.erb
<script>
var lock = new Auth0Lock('<%= ENV['AUTH0_CLIENT_ID'] %>', '<%= ENV['AUTH0_CLIENT_DOM'] %>', {
  closable: true, autoclose: true,
  allowSignUp: false,
  initialScreen: 'login',
  theme: {
    logo: '//res.cloudinary.com/instilla/image/upload/s--1Q_ebjeN--/c_scale,h_56/v1471133824/kapiten-logo_u9kxv6.png',
    primaryColor: '#39D5FF',
    labeledSubmitButton: false
  },
  languageDictionary: {
    emailInputPlaceholder: "alamat email",
    forgotPasswordAction: "Lupa password kamu? ",
    loginLabel: "Log in",
    loginWithLabel: "Masuk dengan %s",
    passwordInputPlaceholder: "password milikmu",
    signUpLabel: "Registrasi",
    signUpWithLabel: "Registrasi dengan %s",
    title: "Autentikasi"
  },
  auth: {
    redirectUrl: '<%= ENV['AUTH0_CALLBACK_URL'] %>',
    responseType: 'code',
    params: {
      scope: 'openid email' // Learn about scopes: //auth0.com/docs/scopes
    }
  }
});

var signup_lock = new Auth0Lock('<%= ENV['AUTH0_CLIENT_ID'] %>', '<%= ENV['AUTH0_CLIENT_DOM'] %>', {
  closable: true, autoclose: true,
  allowLogin: false,
  additionalSignUpFields: [{
    name: 'name',
    placeholder: 'nama lengkapmu',
    icon: '//res.cloudinary.com/instilla/image/upload/s--_7ePm2Yr--/c_scale,w_12/v1474296650/avatar/profile-42914_640.png'
  }],
  theme: {
    logo: '//res.cloudinary.com/instilla/image/upload/s--1Q_ebjeN--/c_scale,h_56/v1471133824/kapiten-logo_u9kxv6.png',
    primaryColor: '#39D5FF',
    labeledSubmitButton: false
  },
  languageDictionary: {
    emailInputPlaceholder: "email address",
    passwordInputPlaceholder: "password milikmu",
    signUpLabel: "Registrasi",
    signUpWithLabel: "Registrasi dengan %s",
    title: "Pendaftaran"
  },
  auth: {
    redirectUrl: '<%= ENV['AUTH0_CALLBACK_URL'] %>',
    responseType: 'code',
    params: {
      scope: 'openid email' // Learn about scopes: //auth0.com/docs/scopes
    }
  }
});

$('.auth0-login').click(function (event) {
  // alert('Hooray!');
  lock.show()
  event.preventDefault(); // Prevent link from following its href
});

$('.auth0-signup').click(function (event) {
  // alert('Hooray!');
  signup_lock.show()
  event.preventDefault(); // Prevent link from following its href
});

</script>

app/views/layouts/_classic_navbar.html.erb
<nav class="navbar navbar-fixed-top navbar-default narrow-nav" id="mobile-navbar">
  <div class="container">
    <div class="navbar-header pull-left">
      <%= link_to '/', class: 'navbar-brand' do %>
        KAPITEN
      <% end %>
    </div>

    <div class="navbar-header pull-right">
      <div class="btn-group" role="group">
        <%= active_link_to App::Naming::CARD, safina_root_path, active: :exclusive, class: "btn btn-simple" %>
        <%= active_link_to '/', active: [['articles'], ['show', 'index']], class: "btn btn-simple" do %>
          Pustaka
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <%= active_link_to admin_root_path, active: :inclusive, class: "btn btn-simple" do %>
              <svg class="svg-icon" viewBox="0 0 20 20">
                <path fill="none" d="M4.68,13.716v-0.169H4.554C4.592,13.605,4.639,13.658,4.68,13.716z M11.931,6.465
                c-0.307-0.087-0.623,0.106-0.706,0.432l-1.389,5.484c-0.901,0.084-1.609,0.833-1.609,1.757c0,0.979,0.793,1.773,1.773,1.773
                c0.979,0,1.773-0.794,1.773-1.773c0-0.624-0.324-1.171-0.812-1.486l1.377-5.439C12.422,6.887,12.239,6.552,11.931,6.465z
                M10.591,14.729H9.408v-1.182h1.183V14.729z M15.32,13.716c0.04-0.058,0.087-0.11,0.126-0.169H15.32V13.716z M10,3.497
                c-3.592,0-6.503,2.911-6.503,6.503H4.68c0-2.938,2.382-5.32,5.32-5.32s5.32,2.382,5.32,5.32h1.182
                C16.502,6.408,13.591,3.497,10,3.497z M10,0.542c-5.224,0-9.458,4.234-9.458,9.458c0,5.224,4.234,9.458,9.458,9.458
                c5.224,0,9.458-4.234,9.458-9.458C19.458,4.776,15.224,0.542,10,0.542z M15.32,16.335v0.167h-0.212
                c-1.407,1.107-3.179,1.773-5.108,1.773c-1.93,0-3.701-0.666-5.108-1.773H4.68v-0.167C2.874,14.816,1.724,12.543,1.724,10
                c0-4.571,3.706-8.276,8.276-8.276c4.57,0,8.275,3.706,8.275,8.276C18.275,12.543,17.126,14.816,15.32,16.335z"></path>
              </svg>
            <% end %>
          <% end %>
        <% end %>
      </div>

    </div>

  </div>
</nav>

app/views/layouts/_debug_dump.html.erb
<%= debug(params) %>
User Info Hash <br>
<%= debug(session[:userinfo]) %>
Current User ID <br>
<%= debug(session[:current_user_id]) %>

app/views/layouts/_disclaimer.html.erb
<div class="row">
  <div class="col-xs-12"  id="disclaimer">
	<small>
	1. PT Kapiten Teknologi Indonesia (Perusahaan) adalah badan hukum yang didirikan berdasarkan Hukum Republik Indonesia, tidak diatur oleh atau dalam pengawasan Otoritas Jasa Keuangan (OJK) di Indonesia. Perusahaan menyediakan layanan perantara: menyediakan peluang dan menyalurkan investasi yang dilakukan oleh individu, organisasi, maupun badan hukum kepada individu atau badan hukum tertentu selaku pemohon.
	</small><br>
	<small>
	2. Perusahaan tidak menyediakan segala bentuk saran atau rekomendasi investasi terkait dengan pilihan-pilihan dalam situs ini. Isi dan materi yang tersedia di sikapiten.com dimaksudkan untuk memberikan informasi dan tidak dianggap sebagai sebuah penawaran, permohonan, undangan, saran, maupun rekomendasi untuk menginvestasikan sekuritas, produk pasar modal, atau jasa keuangan lainnya. Perusahaan dalam memberikan jasanya hanya terbatas pada fungsi administratif.
	</small><br>
	<small>
	3. Dana investasi yang ditempatkan di rekening Kapiten adalah tidak dan tidak akan dianggap sebagai simpanan yang diselenggarakan oleh Perusahaan seperti diatur dalam Peraturan Perundang-Undangan tentang Perbankan di Indonesia.  Perusahaan atau setiap Direktur, Pegawai, Karyawan, Wakil, Afiliasi, atau Agen-Agennya tidak memiliki tanggung jawab terkait dengan segala gangguan atau masalah yang terjadi atau yang dianggap terjadi, yang disebabkan oleh minimnya persiapan atau publikasi dari materi yang tercantum pada situs Perusahaan.
	</small>    
  </div>  
</div>

app/views/layouts/_footer.html.erb
<div class="fh5co-footer-style-2">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-4">
        <div class="fh5co-logo"><%= page_root %> <br>
        <span>PT Kapiten Teknologi Indonesia © 2016</span></div>
      </div>
      <div class="col-sm-6 col-sm-push-0 col-md-4 col-md-push-4 footer-style-2-link">
        <ul>
          <li><%= link_to 'Tentang Kami', '/id/about' %></li>
          <li><%= link_to App::Naming::CARD, safina_root_path %></li>
          <li><%= link_to App::Naming::BLOG, root_path %></li>
        </ul>
      </div>
      <div class="col-sm-6 col-sm-pull-0 col-md-4 col-md-pull-4 footer-style-2-link social-links">
        <ul>
          <li>
            <a href="https://www.facebook.com/groups/majlis.muamalah" target= "_blank">
              <svg class="svg-icon" viewBox="0 0 20 20">
                <path fill="none" d="M14.9,6.707c-0.804-2.497-3.649-4.351-7.035-4.351c-4.008,0-7.27,2.594-7.27,5.782
                c0,2.163,1.516,4.133,3.903,5.122v3.091c0,0.251,0.144,0.478,0.372,0.586c0.087,0.042,0.182,0.062,0.276,0.062
                c0.148,0,0.295-0.051,0.412-0.15l3.678-3.038c0.14-0.022,0.275-0.057,0.413-0.084c0.655,0.666,1.544,1.185,2.607,1.46
                c0.198,0.051,0.401,0.094,0.608,0.125l2.641,2.182c0.118,0.099,0.264,0.15,0.413,0.15c0.094,0,0.188-0.02,0.276-0.062
                c0.228-0.108,0.372-0.335,0.372-0.586v-2.135c1.74-0.761,2.84-2.231,2.84-3.846C19.405,8.862,17.456,7.073,14.9,6.707z
                 M8.885,12.552c-0.019,0.003-0.032,0.018-0.051,0.022c-0.101,0.022-0.2,0.056-0.281,0.123l-2.76,2.28v-2.161
                c0-0.275-0.175-0.521-0.434-0.612C3.253,11.467,1.89,9.871,1.89,8.138c0-2.474,2.68-4.487,5.975-4.487
                c2.604,0,4.801,1.265,5.617,3.014c0.187,0.401,0.302,0.823,0.33,1.268c0.005,0.069,0.028,0.134,0.028,0.205
                c0,1.819-1.481,3.438-3.706,4.129c-0.115,0.037-0.224,0.08-0.343,0.111C9.497,12.455,9.196,12.513,8.885,12.552z M15.703,13.809
                c-0.259,0.091-0.434,0.336-0.434,0.612v1.199l-1.723-1.422c-0.095-0.079-0.211-0.129-0.333-0.144
                c-0.219-0.028-0.431-0.068-0.636-0.121c-0.545-0.14-1.023-0.364-1.433-0.64c2.423-0.969,3.99-2.942,3.99-5.155
                c0-0.024-0.004-0.047-0.005-0.071c1.718,0.385,2.98,1.553,2.98,2.948C18.11,12.202,17.165,13.299,15.703,13.809z"></path>
                <path fill="none" d="M4.68,7.591h6.167c0.358,0,0.648-0.29,0.648-0.648s-0.29-0.648-0.648-0.648H4.68
                c-0.358,0-0.648,0.29-0.648,0.648S4.323,7.591,4.68,7.591z"></path>
                <path fill="none" d="M8.709,8.636H4.68c-0.358,0-0.648,0.29-0.648,0.648c0,0.358,0.29,0.648,0.648,0.648h4.028
                c0.358,0,0.648-0.29,0.648-0.648C9.356,8.926,9.067,8.636,8.709,8.636z"></path>
              </svg>
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/kapitenmuamalah" target= "_blank">
              <svg class="svg-icon" viewBox="0 0 20 20">
                <path fill="none" d="M11.344,5.71c0-0.73,0.074-1.122,1.199-1.122h1.502V1.871h-2.404c-2.886,0-3.903,1.36-3.903,3.646v1.765h-1.8V10h1.8v8.128h3.601V10h2.403l0.32-2.718h-2.724L11.344,5.71z"></path>
              </svg>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_google_analytics_script.html.erb
<% if Rails.env == "production"  %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push( ['_setAccount', "#{ENV['GO_ANL_ID']"] );
  _gaq.push( ['_trackPageview'] );

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>

app/views/layouts/_header_wrapper.html.erb
<header class="main-header">
  <!-- Logo -->
  <%= link_to root_url(subdomain: ''), class: 'logo' do %>
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>KAPI</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Kapiten</b></span>
  <% end %>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- If want to put message inbox, put it right here -->
        <!-- If want to put notifications, put it right here -->
        <!-- Notifications: style can be found in dropdown.less -->

        <li class="dropdown messages-menu">
          <%= link_to user_root_path do %>
            <i class="fa fa-flag"></i>
          <% end %>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= render_user_thumb(current_user, 'user-image') %>
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= render_user_thumb(current_user, 'img-circle') %>
              <p>
                <%= current_user.name %>
                <small>Member since <%= time_ago_in_words(current_user.created_at) %> ago</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="col-xs-5 text-center">
                <%= link_to "Akun", profile_url(subdomain: ''), remote: true %>
              </div>
              <div class="col-xs-2 text-center">
              </div>
              <div class="col-xs-5 text-center">
                <%= link_to "Sign out", destroy_user_session_path, data:{method: :delete}, class: "btn btn-default btn-flat"%>
              </div>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <!--  -->
              </div>
              <div class="pull-right">
                <%= %>
              </div>
            </li>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
<!--         <li>
          <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
        </li> -->
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_heap_script.html.erb
<% if Rails.env.staging? || Rails.env.development? %>
  <script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("538021880");
  </script>
<% elsif Rails.env.production? %>
  <script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("2958547296");
</script>  
<% end %>

app/views/layouts/_language_selector.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <%= language_picker %>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li>
        <%= link_to t('menu.languages.en'), change_locale_path(:en) %>
      </li>
      <li>
        <%= link_to t('menu.languages.id'), change_locale_path(:id) %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
	<% if msg.is_a?(String) %>
	<div class="alert alert-<%= name == "notice" ? "success" : "danger" %> floating-alert">
	  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
	  <%= content_tag :div, msg, :id => "flash_#{name}", class: 'alert-container' %>
	</div>
	<% end %>
<% end %>

app/views/layouts/_sidebar_wrapper.html.erb
<div id="sidebar-wrapper">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <%= link_to 'Menu', admin_root_path %>
    </li>
    <li class="">
      <%= active_link_to 'Articles', admin_articles_path, :active => :exclusive, :wrap_tag => :li %>
    </li>
    <li class="">
      <%= active_link_to 'Users', admin_users_path, :active => :exclusive, :wrap_tag => :li %>
    </li>
    <li class="treeview">
    </li>
  </ul>
</div>

app/views/layouts/_wrapper.html.erb
<div class="wrapper">

  <%= render 'layouts/header_wrapper' %>
  
  <!-- Left side column. contains the logo and sidebar -->
  <%= render 'layouts/sidebar_wrapper' %>


  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">

      <!-- Main row -->
      <div class="row">
        <!-- Left col -->
        <section class="col-lg-12 connectedSortable" style="padding-left: 0px; padding-right: 0px;">
          <%= render 'layouts/messages' %>
          <div class="col-md-10 col-md-offset-1" id="medium-wrap" style="padding-top: 20px;">	
          	<%= yield %>
          </div>
          
        </section> <!-- /.Left col -->
        
        <!-- right col (We are only adding the ID to make the widgets sortable)-->
<!--             <section class="col-lg-5 connectedSortable">

        </section>-->
      </div><!-- /.row (main row) -->

    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.4.0
    </div>
    <strong>&copy; 2016 <a href="https://sikapiten.com">Kapiten</a>.</strong>.
  </footer>

  <!-- Control Sidebar -->
  <%= render 'layouts/aside_control' %>
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div><!-- ./wrapper -->

app/views/layouts/safina.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="SE_GXuKS4WokTiQ1_kpgnruK1g8zDANghc1Qrz_mnpw" />
  <%= favicon_link_tag App::Source::ICON %>
  <%= display_meta_tags site: 'Kapiten', reverse: true, icon: App::Source::ICON %>
  <% if Rails.env.staging? || admin_controller? %>
    <% set_meta_tags nofollow: true, noindex: true  %>
  <% end %>
  <!-- Theme style  -->
  <%= stylesheet_link_tag 'safina', media: 'all' %>
  <%= javascript_include_tag 'safina', 'data-turbolinks-track' => true %>
  <!-- Modernizr JS -->
  <!-- FOR IE9 below -->
  <!--[if lt IE 9]>
  <script src="js/respond.min.js"></script>
  <![endif]-->
  <%= render 'layouts/heap_script' %>
  <%= render 'layouts/google_analytics_script' %>
  <script src="https://embed.small.chat/T0VQQGKNYG59QDQ98S.js" async></script>
</head>
<body>
  <div class="fh5co-loader"></div>

  <%= render 'safina/navigation' %>

  <div id="page">
    <%= yield %>

    <%= render 'safina/footer' %>
  </div>
</body>
</html>